### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26x0

### Add to the source dirs
CONTIKI_TARGET_DIRS += launchpad_vela/cc2650

### Include the common launchpad makefile
include $(PLATFORM_ROOT_DIR)/launchpad_vela/Makefile.launchpad_vela
